import streamlit as st
import pandas as pd

# =========================
# PAGE CONFIG
# =========================

st.set_page_config(
    page_title="Explainable AI",
    page_icon="🔍",
    layout="wide"
)

# =========================
# FETCH PATIENT DATA
# =========================

patient_name = st.session_state.get("patient_name", "Not Available")
age = st.session_state.get("age", "Not Available")
gender = st.session_state.get("gender", "Not Available")
patient_id = st.session_state.get("patient_id", "Not Available")

# =========================
# FETCH PREDICTION DATA
# =========================

prediction = st.session_state.get("prediction", "Not Available")
confidence = st.session_state.get("confidence", 0)

try:
    confidence = float(confidence)
except:
    confidence = 0

# =========================
# PAGE TITLE
# =========================

st.title("🔍 Explainable AI Dashboard")

st.markdown("""
### Understanding the AI Decision

This page provides transparent insights into how NeuroSense AI
arrived at its prediction. The goal is to help clinicians and
researchers better understand the factors influencing the model's
decision-making process.
""")

st.divider()

# =========================
# PATIENT INFORMATION
# =========================

st.subheader("👤 Patient Information")

col1, col2 = st.columns(2)

with col1:
    st.info(f"""
**Patient Name:** {patient_name}

**Age:** {age}

**Gender:** {gender}
""")

with col2:
    st.info(f"""
**Patient ID:** {patient_id}

**Assessment Status:** Completed

**Model Used:** CNN MRI Classifier
""")

st.divider()

# =========================
# PREDICTION SUMMARY
# =========================

st.subheader("🧠 Prediction Summary")

col1, col2 = st.columns(2)

with col1:
    st.metric(
        label="Prediction",
        value=prediction
    )

with col2:
    st.metric(
        label="Confidence",
        value=f"{confidence:.2f}%"
    )

st.divider()

# =========================
# FEATURE IMPORTANCE
# =========================

st.subheader("📊 Feature Importance Analysis")

feature_data = pd.DataFrame({
    "Feature": [
        "Brain Tissue Changes",
        "Ventricular Enlargement",
        "Memory Region Impact",
        "Neurodegenerative Markers"
    ],
    "Importance": [90, 80, 75, 85]
})

st.bar_chart(
    feature_data.set_index("Feature")
)

st.info("""
The AI model focuses on structural patterns observed in MRI scans.

Key factors considered include:

• Brain tissue changes

• Ventricular enlargement

• Memory-related region abnormalities

• Neurodegenerative indicators
""")

st.divider()

# =========================
# MODEL INTERPRETATION
# =========================

st.subheader("🤖 Model Interpretation")

st.write("""
The CNN model analyzes MRI images and extracts visual patterns
associated with different stages of cognitive decline.

The prediction is generated by comparing learned features from
thousands of MRI scans used during training.
""")

if prediction != "Not Available":
    st.success(f"""
### Why This Prediction?

The model detected patterns consistent with:

**{prediction}**

Confidence Level:

**{confidence:.2f}%**

These findings are based on the MRI features that the model
identified as most relevant during inference.
""")
else:
    st.warning(
        "No prediction available. Please upload and analyze an MRI scan first."
    )

st.divider()

# =========================
# CLINICAL INTERPRETATION
# =========================

st.subheader("🏥 Clinical Interpretation")

interpretation = {
    "Non Demented":
        "No significant signs of dementia were detected by the AI model.",

    "Very Mild Dementia":
        "Very early cognitive decline may be present. Further clinical evaluation is recommended.",

    "Mild Dementia":
        "The findings suggest mild cognitive impairment that may require additional assessment.",

    "Moderate Dementia":
        "The prediction indicates noticeable cognitive decline that may affect daily functioning.",

    "Severe Dementia":
        "The prediction suggests advanced dementia-related changes and immediate clinical attention may be necessary."
}

st.warning(f"""
{interpretation.get(
    prediction,
    "Clinical interpretation is unavailable."
)}

This prediction is intended as a clinical decision-support tool.

Final diagnosis should always be confirmed by qualified healthcare professionals.
""")

st.divider()

# =========================
# TRANSPARENCY INSIGHTS
# =========================

st.subheader("🔎 AI Transparency Insights")

st.markdown("""
NeuroSense AI has been designed to improve trust and interpretability.

The system provides:

- Transparent prediction summaries
- Confidence estimates
- MRI feature contribution analysis
- Clinically meaningful explanations
- Decision-support insights for healthcare professionals

These explanations help users understand not only *what* the model predicts,
but also *why* the prediction may have been made.
""")

st.divider()

# =========================
# RECOMMENDATIONS
# =========================

st.subheader("💡 Recommendations")

if prediction == "Non Demented":
    recommendations = [
        "Continue routine health monitoring.",
        "Maintain a healthy lifestyle and cognitive activities.",
        "Schedule regular medical check-ups."
    ]

elif prediction in ["Very Mild Dementia", "Mild Dementia"]:
    recommendations = [
        "Consult a neurologist for further assessment.",
        "Perform additional cognitive evaluations.",
        "Monitor cognitive changes over time.",
        "Schedule follow-up MRI examinations."
    ]

elif prediction in ["Moderate Dementia", "Severe Dementia"]:
    recommendations = [
        "Seek specialist neurological consultation promptly.",
        "Develop a patient care and support plan.",
        "Monitor disease progression regularly.",
        "Review medications and treatment options.",
        "Schedule periodic follow-up assessments."
    ]

else:
    recommendations = [
        "Upload and analyze an MRI scan to generate recommendations."
    ]

for recommendation in recommendations:
    st.markdown(f"- {recommendation}")

st.divider()

# =========================
# FUTURE ENHANCEMENTS
# =========================

st.subheader("🚀 Future Explainability Features")

st.markdown("""
The following explainability capabilities can be integrated in future versions:

- Grad-CAM Visual Explanations
- Attention Heatmaps
- Brain Region Highlighting
- Saliency Maps
- Confidence Visualization
- Advanced Clinical Insight Reports
- Longitudinal Patient Tracking
- Explainable AI Dashboards for Clinicians
""")

st.divider()

# =========================
# DISCLAIMER
# =========================

st.caption("""
NeuroSense AI is intended to assist healthcare professionals and should not be used as a standalone diagnostic tool.

Hackathon Demonstration Version • Explainable AI Module • 2025
""")
