import streamlit as st
import pandas as pd

# =========================
# PAGE CONFIG
# =========================

st.set_page_config(
    page_title="Explainable AI",
    page_icon="🔍",
    layout="wide"
)

# =========================
# FETCH PATIENT DATA
# =========================

patient_name = st.session_state.get("patient_name", "Not Available")
age = st.session_state.get("age", "Not Available")
gender = st.session_state.get("gender", "Not Available")
patient_id = st.session_state.get("patient_id", "Not Available")

# Demo values
prediction = "Moderate Dementia"
confidence = 99

# =========================
# PAGE TITLE
# =========================

st.title("🔍 Explainable AI Dashboard")

st.markdown("""
### Understanding the AI Decision

This page explains how NeuroSense AI arrived at its prediction
and provides transparent insights for clinicians and researchers.
""")

st.divider()

# =========================
# PATIENT INFORMATION
# =========================

st.subheader("👤 Patient Information")

col1, col2 = st.columns(2)

with col1:
    st.info(f"""
**Patient Name:** {patient_name}

**Age:** {age}

**Gender:** {gender}
""")

with col2:
    st.info(f"""
**Patient ID:** {patient_id}

**Assessment:** Completed

**Model:** CNN MRI Classifier
""")

st.divider()

# =========================
# PREDICTION SUMMARY
# =========================

st.subheader("🧠 Prediction Summary")

col1, col2 = st.columns(2)

with col1:
    st.metric(
        "Prediction",
        prediction
    )

with col2:
    st.metric(
        "Confidence",
        f"{confidence}%"
    )

st.divider()

# =========================
# FEATURE IMPORTANCE
# =========================

st.subheader("📊 Feature Importance Analysis")

feature_data = pd.DataFrame({
    "Feature": [
        "Brain Tissue Changes",
        "Ventricular Enlargement",
        "Memory Region Impact",
        "Neurodegenerative Markers"
    ],
    "Importance": [90, 80, 75, 85]
})

st.bar_chart(
    feature_data.set_index("Feature")
)

st.info("""
The model focuses on structural patterns observed in MRI scans.

Key factors considered:

• Brain tissue changes

• Ventricular enlargement

• Memory-related region abnormalities

• Neurodegenerative indicators
""")

st.divider()

# =========================
# MODEL INTERPRETATION
# =========================

st.subheader("🤖 Model Interpretation")

st.write("""
The CNN model analyzes MRI images and extracts visual patterns
associated with different stages of cognitive decline.

The prediction is generated by comparing learned features from
thousands of MRI scans used during training.
""")

st.success(f"""
### Why This Prediction?

The model detected patterns consistent with:

**{prediction}**

Confidence Level:

**{confidence}%**
""")

st.divider()

# =========================
# CLINICAL NOTE
# =========================

st.subheader("🏥 Clinical Interpretation")

st.warning("""
This prediction is intended as a decision-support tool.

Final diagnosis should always be confirmed by qualified
healthcare professionals.

Additional neurological assessment is recommended.
""")

st.divider()

# =========================
# RECOMMENDATIONS
# =========================

st.subheader("💡 Recommendations")

st.markdown("""
- Consult a neurologist.
- Perform additional cognitive assessments.
- Schedule follow-up MRI scans.
- Monitor disease progression regularly.
- Review patient history and symptoms.
""")

st.divider()

# =========================
# FUTURE ENHANCEMENTS
# =========================

st.subheader("🚀 Future Explainability Features")

st.markdown("""
- Grad-CAM Visual Explanations
- Brain Region Highlighting
- Confidence Heatmaps
- AI Attention Maps
- Advanced Clinical Insights
- Longitudinal Patient Tracking
""")

st.divider()

st.caption(
    "NeuroSense AI • Explainable AI Module • Hackathon 2025"
)